# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e1b5fa17526d6bcc57bba5046d066ed650d8818f6b43e074412fc3da1396176e183084cacb74bd2c2ad60db70aac62c3ff7d704036c437d67aecc3e0bc06491

test:
  secret_key_base: 5b47737cfd836696f1a8792fcc94c90c4a2fc24ccf4c27125e6c55a6f2873f2769d6d8ba938d1b7987a20455f3f3a62c806387e6737b2543c11c8e579c8263aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
